// <auto-generated />
using EFSamples.StudentModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFSamples.Migrations
{
    [DbContext(typeof(StudentModelContext))]
    partial class StudentModelContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("EFSamples.StudentModel.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Section")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("EFSamples.StudentModel.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GradeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StudentName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GradeId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("EFSamples.StudentModel.StudentAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("StudentAddresses");
                });

            modelBuilder.Entity("EFSamples.StudentModel.StudentAddressFKAnnotation", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("StudentAddressFKAnnotations");
                });

            modelBuilder.Entity("EFSamples.StudentModel.StudentAddressUseFluent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudentForeignKey")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StudentForeignKey")
                        .IsUnique();

                    b.ToTable("StudentAddressUseFluents");
                });

            modelBuilder.Entity("EFSamples.StudentModel.Student", b =>
                {
                    b.HasOne("EFSamples.StudentModel.Grade", "Grade")
                        .WithMany("Students")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grade");
                });

            modelBuilder.Entity("EFSamples.StudentModel.StudentAddress", b =>
                {
                    b.HasOne("EFSamples.StudentModel.Student", "Student")
                        .WithOne("Address")
                        .HasForeignKey("EFSamples.StudentModel.StudentAddress", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("EFSamples.StudentModel.Address", "HomeAddress", b1 =>
                        {
                            b1.Property<int>("StudentAddressId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Address1")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Address2")
                                .HasColumnType("TEXT");

                            b1.Property<string>("City")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Country")
                                .HasColumnType("TEXT");

                            b1.Property<string>("State")
                                .HasColumnType("TEXT");

                            b1.Property<int>("ZipCode")
                                .HasColumnType("INTEGER");

                            b1.HasKey("StudentAddressId");

                            b1.ToTable("StudentAddresses");

                            b1.WithOwner()
                                .HasForeignKey("StudentAddressId");
                        });

                    b.Navigation("HomeAddress");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EFSamples.StudentModel.StudentAddressFKAnnotation", b =>
                {
                    b.HasOne("EFSamples.StudentModel.Student", "Student")
                        .WithOne("AnnotationAddress")
                        .HasForeignKey("EFSamples.StudentModel.StudentAddressFKAnnotation", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("EFSamples.StudentModel.Address", "HomeAddress", b1 =>
                        {
                            b1.Property<int>("StudentAddressFKAnnotationId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Address1")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Address2")
                                .HasColumnType("TEXT");

                            b1.Property<string>("City")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Country")
                                .HasColumnType("TEXT");

                            b1.Property<string>("State")
                                .HasColumnType("TEXT");

                            b1.Property<int>("ZipCode")
                                .HasColumnType("INTEGER");

                            b1.HasKey("StudentAddressFKAnnotationId");

                            b1.ToTable("StudentAddressFKAnnotations");

                            b1.WithOwner()
                                .HasForeignKey("StudentAddressFKAnnotationId");
                        });

                    b.Navigation("HomeAddress");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EFSamples.StudentModel.StudentAddressUseFluent", b =>
                {
                    b.HasOne("EFSamples.StudentModel.Student", "Student")
                        .WithOne("FluentAddress")
                        .HasForeignKey("EFSamples.StudentModel.StudentAddressUseFluent", "StudentForeignKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("EFSamples.StudentModel.Address", "HomeAddress", b1 =>
                        {
                            b1.Property<int>("StudentAddressUseFluentId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Address1")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Address2")
                                .HasColumnType("TEXT");

                            b1.Property<string>("City")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Country")
                                .HasColumnType("TEXT");

                            b1.Property<string>("State")
                                .HasColumnType("TEXT");

                            b1.Property<int>("ZipCode")
                                .HasColumnType("INTEGER");

                            b1.HasKey("StudentAddressUseFluentId");

                            b1.ToTable("StudentAddressUseFluents");

                            b1.WithOwner()
                                .HasForeignKey("StudentAddressUseFluentId");
                        });

                    b.Navigation("HomeAddress");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EFSamples.StudentModel.Grade", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("EFSamples.StudentModel.Student", b =>
                {
                    b.Navigation("Address");

                    b.Navigation("AnnotationAddress");

                    b.Navigation("FluentAddress");
                });
#pragma warning restore 612, 618
        }
    }
}
